# Generated by Django 4.0.2 on 2022-03-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_customer_user_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
