# Generated by Django 4.0.2 on 2022-03-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pe', 'Pending'), ('A', 'Accepted'), ('Pa', 'Packed'), ('OTW', 'On the way'), ('D', 'Delivered'), ('C', 'Cancel')], default='Pending', max_length=10),
        ),
    ]
