# Generated by Django 4.0.2 on 2022-03-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pe', 'Pending'), ('A', 'Accepted'), ('Pa', 'Packed'), ('OTW', 'On the way'), ('D', 'Delivered'), ('C', 'Cancel')], default='Pe', max_length=10),
        ),
    ]
