# Generated by Django 4.0.2 on 2022-03-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
